### ISSUE TITLE
corrupted heap

### ISSUE THREAD

**Issue by zdila** [mongoose-os-libs/mqtt#10]
ESP32, mos 2.13.1

Sometimes our app crashes on heap corruption. It could be related to mqtt. If you don't think so then we apologize and please close this report.

In our app we use no dynamic memory allocation.

```
[Apr 29 09:30:57.782] CORRUPT HEAP: multi_heap.c:523 detected at 0x3ffe0b44
[Apr 29 09:30:57.826] abort() was called at PC 0x40092c77 on core 0
[Apr 29 09:30:57.826] 
[Apr 29 09:30:57.826] Backtrace: 0x400934d7 0x40093659 0x40092c77 0x40093185 0x40081a89 0x40081af5 0x40081e75 0x4000bedd 0x401b7296 0x401b72f2 0x401b7cac 0x401b9a39 0x400fa751 0x400e60e6 0x400e65a1 0x400f9d11 0x400e267c 0x40083b51
[Apr 29 09:30:57.826] 
[Apr 29 09:30:57.826] --- BEGIN CORE DUMP ---
[Apr 29 09:30:57.826] mos: catching core dump
[Apr 29 09:31:00.667] ..............
[Apr 29 09:31:38.040] ---- END CORE DUMP ----
[Apr 29 09:31:38.053] mos: wrote to /home/martin/m/scoorie/master/core-master-esp32-20190429-093138.197718815 (463091 bytes)
[Apr 29 09:31:38.054] mos: analyzing core dump
Core dump by master/esp32 1.0 20190429-070737/g9eb0b2c-master-dirty
Using ELF file at: /home/martin/m/scoorie/master/build/objs/master.elf
Using Docker image: docker.io/mgos/esp32-build:3.2-r4
Running docker run --rm -v /home/martin/m/scoorie/master/build/objs/master.elf:/fw.elf -v /home/martin/m/scoorie/master/core-master-esp32-20190429-093138.197718815:/core -v /home/martin/m/scoorie/master:/home/martin/m/scoorie/master docker.io/mgos/esp32-build:3.2-r4 bash -c /usr/local/bin/serve_core.py --rom=/opt/Espressif/rom/rom.bin --rom_addr=0x40000000 --xtensa_addr_fixup=true /fw.elf /core & $MGOS_TARGET_GDB /fw.elf -ex 'target remote 127.0.0.1:1234' -ex 'set confirm off' -ex bt -ex quit
GNU gdb (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-build_pc-linux-gnu --target=xtensa-esp32-elf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /fw.elf...done.
Remote debugging using 127.0.0.1:1234
0x400934d7 in invoke_abort ()
    at /opt/Espressif/esp-idf/components/esp32/panic.c:155
155	        *((int *) 0) = 0;
#0  0x400934d7 in invoke_abort ()
    at /opt/Espressif/esp-idf/components/esp32/panic.c:155
#1  0x4009365c in abort ()
    at /opt/Espressif/esp-idf/components/esp32/panic.c:170
#2  0x40092c7a in multi_heap_assert (condition=false, line=523, 
    address=1073613636, 
    format=0x3ffc028d "CORRUPT HEAP: multi_heap.c:%d detected at 0x%08x\n")
    at /opt/Espressif/esp-idf/components/heap/multi_heap_platform.h:54
#3  0x40093188 in multi_heap_realloc_impl (heap=0x3ffe0440, p=0x3ffe0b48, 
    size=1164) at /opt/Espressif/esp-idf/components/heap/multi_heap.c:523
#4  0x40081a8c in heap_caps_realloc (ptr=0x3ffe0b48, size=1164, caps=6144)
    at /opt/Espressif/esp-idf/components/heap/heap_caps.c:298
#5  0x40081af8 in heap_caps_realloc_default (ptr=0x3ffe0b48, size=1164)
    at /opt/Espressif/esp-idf/components/heap/heap_caps.c:176
#6  0x40081e78 in _realloc_r (r=0x3ffc7e60 <mgos_task_tcb+112>, 
    ptr=0x3ffe0b48, size=1164)
    at /opt/Espressif/esp-idf/components/newlib/syscalls.c:47
#7  0x4000bee0 in ?? ()
#8  0x401b7299 in mbuf_insert (a=0x3ffdfe1c, off=28, buf=0x3ffcd498 <buffer>, 
    len=1008) at common/mbuf.c:91
#9  0x401b72f5 in mbuf_append (a=0x3ffdfe1c, buf=0x3ffcd498 <buffer>, 
    len=1008) at common/mbuf.c:114
#10 0x401b7caf in mg_send (nc=0x3ffdfde4, buf=0x3ffcd498 <buffer>, len=1008)
    at mongoose/src/mg_net.c:571
#11 0x401b9a3c in mg_mqtt_publish (nc=0x3ffdfde4, 
    topic=0x3ffc9db0 <mgos_task_stack+7764> "/scoorie/esp32_8E2570", 
    message_id=<optimized out>, flags=<optimized out>, 
    data=0x3ffcd498 <buffer>, len=1008) at mongoose/src/mg_mqtt.c:374
#12 0x400fa754 in mgos_mqtt_pub (
    topic=0x3ffc9db0 <mgos_task_stack+7764> "/scoorie/esp32_8E2570", 
    message=0x3ffcd498 <buffer>, len=1008, qos=1, retain=false)
    at /home/martin/m/scoorie/master/deps/mqtt/src/mgos_mqtt.c:511
#13 0x400e60e9 in dlog_write (source=0 '\000', type=<optimized out>, 
    data=0x3ffc9e30 <mgos_task_stack+7892>, len=12)
    at /home/martin/m/scoorie/master/src/datalogger.c:80
#14 0x400e65a4 in mpu_callback (accel=0x3ffc9e76 <mgos_task_stack+7962>, 
    gyro=0x3ffc9e70 <mgos_task_stack+7956>)
    at /home/martin/m/scoorie/master/src/master.c:182
#15 0x400f9d14 in int_cb (pin=<optimized out>, arg=0x0)
    at /home/martin/m/scoorie/common/src/mpu6050.c:69
#16 0x400e267f in mgos_gpio_int_cb (arg=0x13)
    at /mongoose-os/fw/src/mgos_gpio.c:111
#17 0x40083b54 in mgos_task (arg=<optimized out>)
    at /home/martin/m/scoorie/master/deps/freertos/src/mgos_freertos.c:220
Detaching from program: /fw.elf, Remote target
Waiting for gdb on 1234
Dump contains FreeRTOS task info
Found core at 23 - 463034
Mapping DRAM: 335872 @ 0x3ffae000
Mapping /opt/Espressif/rom/rom.bin at 0x40000000
Mapping /fw.elf .iram0.vectors: 1024 @ 0x40080000
Mapping /fw.elf .iram0.text: 89161 @ 0x40080400
Mapping /fw.elf .dram0.data: 10780 @ 0x3ffbdb60
Mapping /fw.elf .dram0.bss: 62912 @ 0x3ffc0580
Mapping /fw.elf .flash.rodata: 243688 @ 0x3f400020
Mapping /fw.elf .flash.text: 1019986 @ 0x400d0018
Loaded core dump from last snippet in  /core
GDB closed the connection
Ending remote debugging.
```

**Comment by zdila** [comment]
Little different crash log:

```
[Apr 29 10:29:50.746] Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
[Apr 29 10:29:50.746] Core 0 register dump:
[Apr 29 10:29:50.746] PC      : 0x400fa32d  PS      : 0x00060830  A0      : 0x801b9b18  A1      : 0x3ffc9cb0  
[Apr 29 10:29:50.746] A2      : 0x000000cc  A3      : 0x00000005  A4      : 0x00000000  A5      : 0x3ffdc1dc  
[Apr 29 10:29:50.746] A6      : 0x3ffca000  A7      : 0x00000005  A8      : 0x80081e68  A9      : 0x3ffc9d80  
[Apr 29 10:29:50.746] A10     : 0x00000002  A11     : 0x3f40a28f  A12     : 0x000000a6  A13     : 0x00000000  
[Apr 29 10:29:50.746] A14     : 0x3ff47024  A15     : 0x00000000  SAR     : 0x0000000d  EXCCAUSE: 0x0000001c  
[Apr 29 10:29:50.789] EXCVADDR: 0x00000000  LBEG    : 0x4000c46c  LEND    : 0x4000c477  LCOUNT  : 0x00000000  
[Apr 29 10:29:50.789] 
[Apr 29 10:29:50.789] Backtrace: 0x400fa32d 0x401b9b15 0x401b8fae 0x401b948a 0x401bb1aa 0x401bb1e7 0x401c8d05 0x401b6a85 0x400839b6 0x40083b51
[Apr 29 10:29:50.789] 
[Apr 29 10:29:50.789] --- BEGIN CORE DUMP ---
[Apr 29 10:29:50.789] mos: catching core dump
[Apr 29 10:29:53.630] ..............
[Apr 29 10:30:30.917] ---- END CORE DUMP ----
[Apr 29 10:30:30.929] mos: wrote to /home/martin/m/scoorie/master/core-master-esp32-20190429-103030.502925915 (462372 bytes)
[Apr 29 10:30:30.930] mos: analyzing core dump
Core dump by master/esp32 1.0 20190429-081944/g9eb0b2c-master-dirty
Using ELF file at: /home/martin/m/scoorie/master/build/objs/master.elf
Using Docker image: docker.io/mgos/esp32-build:3.2-r4
Running docker run --rm -v /home/martin/m/scoorie/master/build/objs/master.elf:/fw.elf -v /home/martin/m/scoorie/master/core-master-esp32-20190429-103030.502925915:/core -v /home/martin/m/scoorie/master:/home/martin/m/scoorie/master docker.io/mgos/esp32-build:3.2-r4 bash -c /usr/local/bin/serve_core.py --rom=/opt/Espressif/rom/rom.bin --rom_addr=0x40000000 --xtensa_addr_fixup=true /fw.elf /core & $MGOS_TARGET_GDB /fw.elf -ex 'target remote 127.0.0.1:1234' -ex 'set confirm off' -ex bt -ex quit
GNU gdb (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-build_pc-linux-gnu --target=xtensa-esp32-elf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /fw.elf...done.
Remote debugging using 127.0.0.1:1234
mgos_mqtt_ev (nc=<optimized out>, ev=5, ev_data=0x0, 
    user_data=<optimized out>)
    at /home/martin/m/scoorie/master/deps/mqtt/src/mgos_mqtt.c:164
164	      int status = *((int *) ev_data);
#0  mgos_mqtt_ev (nc=<optimized out>, ev=5, ev_data=0x0, 
    user_data=<optimized out>)
    at /home/martin/m/scoorie/master/deps/mqtt/src/mgos_mqtt.c:164
#1  0x401b9b18 in mqtt_handler (nc=0x3ffdc1dc, ev=5, ev_data=0x0, 
    user_data=0x0) at mongoose/src/mg_mqtt.c:144
#2  0x401b8fb1 in mg_call (nc=0x3ffdc1dc, 
    ev_handler=0x401b9af8 <mqtt_handler>, user_data=0x0, ev=5, ev_data=0x0)
    at mongoose/src/mg_net.c:96
#3  0x401b948d in mg_close_conn (conn=0x3ffdc1dc) at mongoose/src/mg_net.c:203
#4  0x401bb1ad in mg_ev_mgr_lwip_process_signals (mgr=<optimized out>)
    at common/platforms/lwip/mg_lwip_ev_mgr.c:71
#5  0x401bb1ea in mg_lwip_if_poll (iface=<optimized out>, timeout_ms=0)
    at common/platforms/lwip/mg_lwip_ev_mgr.c:131
#6  0x401c8d08 in mg_mgr_poll (m=0x3ffcfb1c <s_mgr>, timeout_ms=0)
    at mongoose/src/mg_net.c:301
#7  0x401b6a88 in mongoose_poll (ms=0)
    at /data/tmp/mos_prebuild/tmp/cesanta/mos-libs/mongoose/src/mgos_mongoose.c:61
#8  0x400839b9 in mgos_mg_poll_cb (arg=<optimized out>)
    at /home/martin/m/scoorie/master/deps/freertos/src/mgos_freertos.c:101
#9  0x40083b54 in mgos_task (arg=<optimized out>)
    at /home/martin/m/scoorie/master/deps/freertos/src/mgos_freertos.c:220
Detaching from program: /fw.elf, Remote target
Waiting for gdb on 1234
Dump contains FreeRTOS task info
Found core at 23 - 462317
Mapping DRAM: 335872 @ 0x3ffae000
Mapping /opt/Espressif/rom/rom.bin at 0x40000000
Mapping /fw.elf .iram0.vectors: 1024 @ 0x40080000
Mapping /fw.elf .iram0.text: 89161 @ 0x40080400
Mapping /fw.elf .dram0.data: 10780 @ 0x3ffbdb60
Mapping /fw.elf .dram0.bss: 62912 @ 0x3ffc0580
Mapping /fw.elf .flash.rodata: 243664 @ 0x3f400020
Mapping /fw.elf .flash.text: 1019954 @ 0x400d0018
Loaded core dump from last snippet in  /core
GDB closed the connection
Ending remote debugging.
```

**Comment by rojer** [comment]
absent further evidence, i'm going to assume this is not related.
